@startuml
set separator none

title Überwachungssystem - Containers

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Mitarbeiter, "Mitarbeiter", $descr="Trägt den Handschuh und erhält Warnungen via Vibration.", $tags="", $link="")

System_Boundary("Überwachungssystem_boundary", "Überwachungssystem", $tags="") {
  Container(Überwachungssystem.Energiemessbox, "Energiemessbox", $techn="OPC UA", $descr="Liefert Messdaten zu Druck und Luftfluss.", $tags="", $link="")
  Container(Überwachungssystem.NodeRed, "NodeRed", $techn="NodeRed (Flow-basiert)", $descr="Liest Messdaten via OPC UA und REST, publiziert sie weiter.", $tags="", $link="")
  Container(Überwachungssystem.ZIGPOS, "ZIGPOS", $techn="Websockets", $descr="Liefert Positionsdaten.", $tags="", $link="")
  Container(Überwachungssystem.MessageBroker, "MessageBroker", $techn="MQTT", $descr="Empfangen und Senden von Daten.", $tags="", $link="")
  Container(Überwachungssystem.Handschuh, "Handschuh", $techn="", $descr="Empfängt Warnungen und gibt Vibration als Feedback an den Mitarbeiter.", $tags="", $link="")
  Container(Überwachungssystem.AAS, "AAS", $techn="", $descr="Empfängt Druckluftdaten.", $tags="", $link="")
  Container(Überwachungssystem.Drools, "Drools", $techn="", $descr="Wertet Geschäftsregeln aus.", $tags="", $link="")
}

Rel(Überwachungssystem.Energiemessbox, Überwachungssystem.NodeRed, "rPressure, rFlow via OPCUA", $techn="", $tags="", $link="")
Rel(Überwachungssystem.ZIGPOS, Überwachungssystem.NodeRed, "Positionsdaten via WEBSOCKETS", $techn="", $tags="", $link="")

Rel_L(Überwachungssystem.NodeRed, Überwachungssystem.Drools, "REST POST: Air", $techn="", $tags="", $link="")
Rel_R(Überwachungssystem.Drools, Überwachungssystem.NodeRed, "Response: hasMalfunction", $techn="", $tags="", $link="")

Rel_L(Überwachungssystem.NodeRed, Überwachungssystem.Drools, "REST POST: Position", $techn="", $tags="", $link="")
Rel_R(Überwachungssystem.Drools, Überwachungssystem.NodeRed, "Response: personInArea", $techn="", $tags="", $link="")

Rel_R(Überwachungssystem.NodeRed, Überwachungssystem.AAS, "REST POST: Air", $techn="", $tags="", $link="")
Rel_L(Überwachungssystem.NodeRed, Überwachungssystem.AAS, "REST POST: hasMalfunction", $techn="", $tags="", $link="")

Rel(Überwachungssystem.NodeRed, Überwachungssystem.MessageBroker, "publish Topic: personInArea, Service Level 1", $techn="", $tags="", $link="")

Rel(Überwachungssystem.AAS, Überwachungssystem.MessageBroker, "publish Topic: Air, Service Level 1", $techn="", $tags="", $link="")
Rel(Überwachungssystem.AAS, Überwachungssystem.MessageBroker, "publish Topic: hasMalfunction, Service Level 1", $techn="", $tags="", $link="")

Rel_L(Überwachungssystem.MessageBroker, Überwachungssystem.Handschuh, "subscribe Topic: hasMalfunction, Service Level 1", $techn="", $tags="", $link="")
Rel_L(Überwachungssystem.MessageBroker, Überwachungssystem.Handschuh, "subscribe Topic: personInArea, Service Level 1", $techn="", $tags="", $link="")

Rel_L(Überwachungssystem.Handschuh, Mitarbeiter, "sendet Warnung (Vibration)", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml

