name: Generate and Publish PDF Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install asciidoctor-pdf
        run: gem install asciidoctor-pdf

      - name: Generate PDF from AsciiDoc
        run: asciidoctor-pdf -o Dokumentation.pdf Dokumentation.adoc

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit PDF file
        run: |
          git add Dokumentation.pdf
          git commit -m "Update documentation PDF" || echo "No changes to commit"
          git push origin main